name: tech_news_app
description: A technology news application with voice search, camera integration, location-based personalisation, push notifications, and social sharing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^7.1.1
  flutter_local_notifications: ^19.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  camera: ^0.11.2
  qr_code_scanner: ^1.0.0-nullsafety.1
  share_plus: ^11.0.0
  speech_to_text: ^7.2.0
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1
  intl: ^0.18.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  sqflite: ^2.3.3+1
  drift: ^2.18.0
  path: ^1.8.3
  firebase_core: ^3.15.2
  firebase_core_web: ^2.24.1
  firebase_auth_web: ^5.15.3
  cloud_firestore_web: ^4.4.12
  flutterfire_cli: ^1.3.1
  firebase_messaging: ^15.2.10
  universal_html: ^2.2.4
  google_sign_in_web: ^1.0.0
  google_sign_in_platform_interface: ^3.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  network_image_mock: ^2.1.1
  firebase_auth_mocks: ^0.14.2
  sqflite_common_ffi: ^2.3.4

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
